// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Maintenance.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Maintenance.Infrastructure.Migrations
{
    [DbContext(typeof(MaintenanceDbContext))]
    [Migration("20260203130001_InitialMaintenance")]
    partial class InitialMaintenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("maintenance")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Maintenance.Domain.Entities.MaintenanceAct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("maintenance_date");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_acts");

                    b.ToTable("maintenance_acts", "maintenance");
                });

            modelBuilder.Entity("Modules.Maintenance.Domain.Entities.MaintenanceOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MaintenanceActId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_act_id");

                    b.Property<Guid>("MechanicId")
                        .HasColumnType("uuid")
                        .HasColumnName("mechanic_id");

                    b.Property<DateTime>("OperationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("operation_date");

                    b.PrimitiveCollection<List<string>>("Tasks")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tasks");

                    b.Property<string>("VehicleNumberPlate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_number_plate");

                    b.HasKey("Id")
                        .HasName("pk_operations");

                    b.HasIndex("MaintenanceActId")
                        .HasDatabaseName("ix_operations_maintenance_act_id");

                    b.ToTable("operations", "maintenance");
                });

            modelBuilder.Entity("Modules.Maintenance.Domain.Entities.MaintenanceOperation", b =>
                {
                    b.HasOne("Modules.Maintenance.Domain.Entities.MaintenanceAct", null)
                        .WithMany("Operations")
                        .HasForeignKey("MaintenanceActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operations_maintenance_acts_maintenance_act_id");
                });

            modelBuilder.Entity("Modules.Maintenance.Domain.Entities.MaintenanceAct", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
