services:
  app:
    image: shipping-modular-monolith
    container_name: mauth_app
    build:
      context: .
      dockerfile: ./ModularMonolith.Host/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_HEADERS=X-Seq-ApiKey=abcde12345
    restart: always
    networks:
      - docker-web
      - shared-network

  postgres:
    image: postgres:latest
    container_name: mauth_postgres
    environment:
      - TZ
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=modular_monolith
    volumes:
      - ./docker_data/pgdata:/var/lib/postgresql/data
    ports:
      - "5450:5432"
    restart: always
    networks:
      - docker-web
      - shared-network

  seq:
    image: datalust/seq:2024.3
    container_name: mauth_seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./docker_data/seq:/data
    ports:
      - "5341:5341"
      - "8081:80"
    networks:
      - docker-web
      - shared-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: mauth_jaeger
    restart: always
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
    networks:
      - docker-web
      - shared-network

  front:
    image: nginx:alpine
    container_name: mauth_front
    restart: always
    ports:
      - "8082:80"
    networks:
      - docker-web
      - shared-network

networks:
  docker-web:
    driver: bridge
  shared-network:
    external: true
