// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.MaintenanceOperations.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.MaintenanceOperations.Infrastructure.Migrations
{
    [DbContext(typeof(MaintenanceOperationsDbContext))]
    partial class MaintenanceOperationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("maintenanceoperations")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.MaintenanceOperations.Domain.Entities.MaintenanceOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MaintenanceActId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_act_id");

                    b.Property<Guid>("MechanicId")
                        .HasColumnType("uuid")
                        .HasColumnName("mechanic_id");

                    b.Property<DateTime>("OperationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("operation_date");

                    b.PrimitiveCollection<List<string>>("Tasks")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tasks");

                    b.Property<string>("VehicleNumberPlate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_number_plate");

                    b.HasKey("Id")
                        .HasName("pk_operations");

                    b.ToTable("operations", "maintenanceoperations");
                });
#pragma warning restore 612, 618
        }
    }
}
