<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="Features\GetWorkflow\GetWorkflow.Handler.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Modules.Common.API\Modules.Common.API.csproj" />
    <ProjectReference Include="..\..\Common\Modules.Common.Application\Modules.Common.Application.csproj" />
    <ProjectReference Include="..\Modules.Workflows.Domain\Modules.Workflows.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />       
  </ItemGroup>

</Project>
